name: Linting
on:
  pull_request:
  push:

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install Style dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_style.txt
      - name: Run linting
        run: make lint
      - name: Run codespell
        run: make codespell
